require("./apiLocations");
require("./modules/login/module");
require("./modules/common/module");
require("./modules/gumgatagdefinition/module");
require("./modules/gumgacustomfield/module");
require("./modules/welcome/module");
require("./modules/account/module");
require('./modules/item/module');
require('./modules/balconista/module');
require('./modules/bibliotecario/module');
require('./modules/livro/module');
require('./modules/periodico/module');
require('./modules/pessoa/module');
require('./modules/usuario/module');
require('./modules/academpdco/module');
require('./modules/emprestimo/module');
require('./modules/reserva/module');
//FIMREQUIRE
